### ISSUE TITLE
Security: Does the restify npm module escape for SQL injection?

### ISSUE THREAD

**Issue by drewrwilson** [drewrwilson/stuffer#3]
Or do I need to do that in the script?

**Comment by m4chinations** [comment]
since we use pg, it should be handled as long as we use the correct calls: https://github.com/brianc/node-postgres/wiki/FAQ#8-does-node-postgres-handle-sql-injection

**Comment by drewrwilson** [comment]
@tennysonholloway thanks for researching this!
